language: node_js
node_js:
- node
install:
- yarn
script:
- npm run test
- npm run build
after_script:
- ls -ltrh dist/
before_install:
- openssl aes-256-cbc -K $encrypted_3e0860eaae83_key -iv $encrypted_3e0860eaae83_iv
  -in ciweb.enc -out ~\/.ssh/ciweb -d
